# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_db', '0004_class_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_time',
            field=models.CharField(blank=True, choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], db_column='CLASS_TIME', max_length=45, null=True),
        ),
    ]
