# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_db', '0007_auto_20180219_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='fees_date',
            field=models.DateTimeField(auto_now_add=True, db_column='FEES_DATE'),
        ),
    ]
