# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-19 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_db', '0009_auto_20180219_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='fees_date',
            field=models.CharField(db_column='FEES_DATE', max_length=45),
        ),
    ]
