# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-19 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_db', '0010_auto_20180219_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank_date',
            field=models.CharField(db_column='RANK_DATE', max_length=45),
        ),
    ]
