# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_db', '0015_auto_20180220_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(db_column='ATT_DATE', primary_key=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('class_field', 'std', 'att_date')]),
        ),
    ]
