# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_db', '0020_auto_20180220_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(db_column='ATT_DATE', primary_key=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='std',
            field=models.ForeignKey(db_column='STD_ID', on_delete=django.db.models.deletion.CASCADE, to='bbc_db.Student'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='std',
            field=models.ForeignKey(db_column='STD_ID', on_delete=django.db.models.deletion.CASCADE, to='bbc_db.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='par',
            field=models.ForeignKey(blank=True, db_column='PAR_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='bbc_db.Parent'),
        ),
    ]
