# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_db', '0025_auto_20180220_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.CharField(db_column='ATT_DATE', max_length=45),
        ),
    ]
